### ISSUE TITLE
Criar site do projeto Ação Jovem na Rede Livre

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/6acaojovem#1]
- [x] criar site http://6acaojovem.redelivre.org.br
- [x] customizar página principal
- [x] criar modelo de página para apresentação dos projetos / postagens
- [x] criar, na seção projetos, as categorias: cuca jangurussu, cuca barra, cuca mondubim + o nome dos projetos

**Comment by Andreqlp** [comment]
Sugestão de layout para a página principal:
![imagem](https://user-images.githubusercontent.com/14170372/27876828-c7e7effa-618e-11e7-9909-f20685c863b7.jpg)

**Comment by eduardaribeiro** [comment]
"Na parte 6° ação jovem" seria como uma logo?

**Comment by Andreqlp** [comment]
Isso, a logo está na pasta compartilhada do docs. 

Documentação para ajudar a trabalhar no divi: https://www.elegantthemes.com/documentation/divi/

**Comment by Andreqlp** [comment]
Proposta de página inicial: http://6acaojovem.redelivre.org.br/inicio/
Proposta de página dos projetos: http://6acaojovem.redelivre.org.br/natora/

**Comment by Andreqlp** [comment]
Proposta de página das postagens: http://6acaojovem.redelivre.org.br/project/1-encontro-cuca-barra/
