### ISSUE TITLE
Tutorial de como inserir os eventos no Mapa Cultural do Cearpa

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/6acaojovem#10]
- [x] criar o agente
- [x] criar um projeto
- [x] criar um evento

**Comment by uira** [comment]
@Andreqlp Para criar uma ocorrência dentro do evento, o Espaço também precisa estar previamente cadastrado.

**Comment by Andreqlp** [comment]
Bem lembrado.

Projeto do 6 Ação Jovem no Mapa Cultural do Ceará: http://mapa.cultura.ce.gov.br/projeto/657/
Espaço Cuca Barra: http://mapa.cultura.ce.gov.br/espacos/edita/49/
Espaço Cuca Jangurussu: http://mapa.cultura.ce.gov.br/espaco/41/
Espaço Cuca Mondubim: http://mapa.cultura.ce.gov.br/espaco/42/

**Comment by Andreqlp** [comment]
## Vídeo parte 1: https://youtu.be/jwuPPsFru0U
- Sobre o Mapa Cutlural do Ceará
- Como criar um agente

## Vídeo parte 2: https://youtu.be/3aIqSpZBELo
- Como criar projetos
- Cadastrar eventos
- Cadastrar espaços
