### ISSUE TITLE
Criar página dos projetos do Cuca Jangurussu

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/6acaojovem#2]
Criar página com a informação dos projetos que estão no drive:
- [x] Simples Cidade
- [x] Festival InModa
- [x] Exposição Pura Pele
- [x] Brotando Vidas
- [x] Rotinas

**Comment by eduardaribeiro** [comment]
Tive dificuldades em abrir o  Email

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-07-14 14:42 GMT-03:00 André Quintino Lopes <notifications@github.com>:
